### ISSUE TITLE
Issue with tailwindcss framework

### ISSUE THREAD

**Issue by LangRizkie** [LottieFiles/lottie-vue#13]
Lottie breaks Tailwind responsiveness, I can't use any responsive breakpoint while using Lottie. The only option I found before this fixed is using prefix on my tailwind project but if you have a lot of files it would take time to change.

update: I'm temporary fix this with
```
document.querySelectorAll('style,link[type="text/css"]')
   .forEach((el) => {
      if (el.innerHTML.includes('.lottie-player')) el.remove()
})
```

**Comment by karamalie** [comment]
hi @LangRizkie 
looking into this. is it possible to help me reproduce your issue so i can check the fixes once they are done

**Comment by karamalie** [comment]
do have a look at v1.0.5 https://www.npmjs.com/package/@lottiefiles/vue-lottie-player
added prefixes to all our css classes so that they wont pollute the global space

**Comment by LangRizkie** [comment]
> do have a look at v1.0.5 https://www.npmjs.com/package/@lottiefiles/vue-lottie-player added prefixes to all our css classes so that they wont pollute the global space

great will update and try it soon! 🤘
