### ISSUE TITLE
Add possibility to hide Spinner before animation

### ISSUE THREAD

**Issue by M00NBOY** [LottieFiles/lottie-vue#18]
Great lib but I have an issue
Even with the exact same code as the doc, there is a green loader when the player is loading before the animation. I can't find a way to hide it, is it possible ?

**Comment by samuelOsborne** [comment]
Hey @M00NBOY ,

You could override the  ```.lf-spinner``` spinner class and put in your own css:

```
.lf-spinner {
display: none;
}
```

Let me know how that works out for you,

Cheers!

**Comment by M00NBOY** [comment]
Thank you @samuelOsborne, it works !
