### ISSUE TITLE
How use mode "bounce" in this wrapper?

### ISSUE THREAD

**Issue by maksimPandabit** [LottieFiles/lottie-vue#19]
i cannot specify PlayMode in this wrapper

**Comment by samuelOsborne** [comment]
Will look in to implementing support @maksimPandabit.

**Comment by samuelOsborne** [comment]
Hi @maksimPandabit you can now use bounce mode on this wrapper with version 1.0.6:

      <lottie-player
        ref="player"
        :autoplay="autoplay"
        :src="src"
        :loop="options.loop"
        :speed="options.speed"
        mode="bounce"
      ></lottie-player>
