### ISSUE TITLE
Cannot find module: '@lottiefiles/vue-lottie-player'

### ISSUE THREAD

**Issue by SkySor44** [LottieFiles/lottie-vue#23]
vue@2.6.14

Reproduced by following installation guide:
- Installed with npm: `npm install --save @lottiefiles/vue-lottie-player`
- `import LottieVuePlayer from "@lottiefiles/vue-lottie-player";` in `main.js`
- `Vue.use(LottieVuePlayer);` below the import but above the `new Vue({)}` instantiation

Looking at the node_module it looks empty: 

![Screen Shot 2022-05-12 at 11 30 30 AM](https://user-images.githubusercontent.com/36673523/168134390-b8fb84f4-f53a-4fcb-a8ce-f2caa33ccb8b.png)

**Comment by samuelOsborne** [comment]
Hi @SkySor44, can you bump your player version to 1.0.7. It should fix the problem, cheers!

**Comment by SkySor44** [comment]
That did the trick! Thank you.

**Comment by SossenSystems** [comment]
Same issue with 1.1.0
TS7016: Could not find a declaration file for module '@lottiefiles/vue-lottie-player'. '/Users/myuser/project/node_modules/@lottiefiles/vue-lottie-player/dist/vue-lottie-player.common.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/lottiefiles__vue-lottie-player` if it exists or add a new declaration (.d.ts) file containing `declare module '@lottiefiles/vue-lottie-player';`
