### ISSUE TITLE
Persist Lottie animation when not looping

### ISSUE THREAD

**Issue by jboctor** [LottieFiles/lottie-vue#26]
The animation I display using Lottie disappears when not looping. I would like to be able to persist the last frame on the page.

![lottie](https://user-images.githubusercontent.com/12699907/172702821-457fe157-821d-4f8a-8dd5-bb3ca5d55b45.gif)
 
The component looks like
```
<lottie-vue-player class="tw-mt-8 tw-w-full tw-h-32"
    :src="`https://assets1.lottiefiles.com/packages/lf20_sonmjuir.json`" 
    :autoplay="true" />
```

**Comment by jboctor** [comment]
Upon further investigation this is NOT an issue with lottie-vue but a bug with Bodymovin/Lottie Player.

**Comment by DubMan21** [comment]
@jboctor did you find a workaround?

**Comment by jboctor** [comment]
@DubMan21 it was an issue with the animations themselves so our designer had to rebuild the animations so they weren't going back to the first frame at the end.

**Comment by vslavov** [comment]
FWIW, this was fixed in lottie-player https://github.com/LottieFiles/lottie-player/issues/164#issuecomment-1180169593
