### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by valoricDe** [LottieFiles/lottie-vue#27]
Hi there, it's more a question than an issue.

I see there is a backgroundStyle prop. Which is always set to 'color'.
Is it possible to have a transparent background?

Cheers

**Comment by samuelOsborne** [comment]
@valoricDe Hi there, the back is set to transparent by default. If you want to set it, use 'transparent' as value.

Cheers!

**Comment by tomastan** [comment]
> @valoricDe Hi there, the back is set to transparent by default. If you want to set it, use 'transparent' as value.

This looks to be not completely true, since it set to white by the component styles:

https://github.com/LottieFiles/lottie-vue/blob/98d3567cf9ea80d6880244181f09adcee75c6174/src/lottie_player.css#L6-L12

to solve that we have to implicitly override it:
```css
	.vue-lottie-player{
		background-color: transparent !important;
	}
```

It would be cleaner if no need to do that.

**Comment by valoricDe** [comment]
Hey there jfyi, I migrated to Vue3 and use Vue3Lottie now. So I will be not of any help anymore.
