### ISSUE TITLE
Warning of security risk occurs due to using eval when bundling with vite

### ISSUE THREAD

**Issue by WANZARGEN** [LottieFiles/lottie-vue#36]
I use `vite@4.3.3`, `@lottiefiles/vue-lottie-player@1.1.0`.
When I build the application, there is a warning as below:
> Use of eval in "../../node_modules/@lottiefiles/vue-lottie-player/dist/vue-lottie-player.common.js" is strongly discouraged as it poses security risks and may cause issues with minification.

I think it's quite critical 🤔

**Comment by samuelOsborne** [comment]
Hi @WANZARGEN eval is used in lottie-web to make use of expressions, unfortunately we can't fix that warning for the moment
