### ISSUE TITLE
Local json instead of url

### ISSUE THREAD

**Issue by atipezda** [LottieFiles/lottie-vue#8]
Is there a possibility to just load json from a file (import / require - webpack) instead of calling the URL.

**Comment by samuelOsborne** [comment]
@atipezda If you put your animations in the public folder, you'll be able to store them locally, and access them relative to the public folder structure

**Comment by Fadil3** [comment]
@samuelOsborne is it possible to load .json from `assets` folder in nuxt.js ?

i have tried this but it show error
```
<lottie-vue-player
        src="~/assets/131015-champion.json"
        :autoplay="true"
        :loop="true"
        :player-controls="false"
        style="width: 100%; height: 400px"
      >
      </lottie-vue-player>
```

the error 
![image](https://user-images.githubusercontent.com/55126764/209121024-0fcb0cbb-8b68-40fb-8e1c-d0d9084fdfac.png)
