### ISSUE TITLE
Vue-lottie-player impact and override project styles by own css styles  

### ISSUE THREAD

**Issue by ybabenkoJapp** [LottieFiles/lottie-vue#9]
Hi guys! I have faced the next issue: the Vue-lottie-player overrides the CSS styles of my project. As I have found,  it adds a new font size for h1 as It is described into the component vue-lottie-player.common.js string 549 exports.push([module.i...]).
I need to save my own CSS styles. 
How to fix it? Could you please help me?

I use Nuxt @ v2.15.8  

"dependencies": {
    "@lottiefiles/lottie-interactivity": "^1.3.4",
    "@lottiefiles/vue-lottie-player": "^1.0.2",
    "vue-awesome-swiper": "^4.1.1",
    "vue-class-component": "^7.2.3",
    "vue-fragment": "^1.5.2",
    "vue-pagination-2": "^3.0.91",
    "vue-property-decorator": "^9.0.0",
    "vuex": "^3.5.1"
  },

**Comment by Yevhenii-Babenko** [comment]
@samuelOsborne if you need more information just ping me

**Comment by samuelOsborne** [comment]
Hi @Yevhenii-Babenko @ybabenkoJapp Can you let me know if v1.0.3 solved your issue?

**Comment by ybabenkoJapp** [comment]
Hi! @samuelOsborne yes, this solution works. Thanks!

**Comment by samuelOsborne** [comment]
Thanks @ybabenkoJapp, closing the issue. :-)
